# -*- coding: utf-8 -*-
"""Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBGlp0usbUaQtj0ZTi2oBD1L7FzlLjgP
"""

!pip install -q langchain-community langchain-core
!pip install -q --upgrade huggingface-hub
!pip install -q --upgrade transformers
!pip install -q --upgrade langchain
!pip install -q --upgrade bitsandbytes>0.37.0
!pip install -q --upgrade accelerate

import torch
import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM
from langchain import LLMChain, HuggingFacePipeline, PromptTemplate
from langchain.memory import ConversationBufferMemory