# -*- coding: utf-8 -*-
"""Indexer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBGlp0usbUaQtj0ZTi2oBD1L7FzlLjgP
"""

# !pip install -q --upgrade transformers
# !pip install -q --upgrade torch
!pip install -q transformers
!pip install -q torch
!pip install -q beautifulsoup4
!pip install -q --upgrade bert_score
!pip install -q sentence-transformers

import time
import pandas as pd
import numpy as np
import string
import re
import os
import torch
import bert_score
from IPython.display import display, HTML
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from transformers import BertTokenizer, BertModel
from sentence_transformers import SentenceTransformer, util
from bs4 import BeautifulSoup