# -*- coding: utf-8 -*-
"""Llama-2 (Recognizing Question Entailment)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Xe2U_4tlo6Z2ni-Rfjzwbm_r8ap2nOq
"""

!pip install -q -U transformers
!pip install -q torchmetrics
!pip install -q pytorch_lightning
!pip install -q bitsandbytes
!pip install -q -U peft
!pip install -q accelerate
!pip install -q trl
!pip install -q tensorboard
!pip install -q datasets
!pip install -q rouge
!pip install -q bert-score

import os
import re
import torch
import warnings
import nltk
import json
import time
import requests
import sklearn
import gc
nltk.download('punkt')

import numpy as np
import pandas as pd
import torch.nn as nn
import bitsandbytes as bnb
import pytorch_lightning as pl
import matplotlib.pyplot as plt
import torch.nn.functional as F

from pytorch_lightning.loggers import TensorBoardLogger
from pytorch_lightning import Callback
from pytorch_lightning.callbacks import ModelCheckpoint
from tensorboard import notebook

from torchmetrics import MetricCollection
from torchmetrics.text.bert import BERTScore
from torchmetrics.text.rouge import ROUGEScore
from torchmetrics.classification import (
    BinaryAccuracy,
    BinaryPrecision,
    BinaryRecall,
    BinaryF1Score
    )

from peft import (
    TaskType,
    PeftModel,
    PeftConfig,
    LoraConfig,
    get_peft_model,
    AutoPeftModelForCausalLM,
    prepare_model_for_kbit_training,
    )

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForCausalLM,
    HfArgumentParser,
    TrainingArguments,
    )

from dataclasses import dataclass, field
from nltk.tokenize import word_tokenize
from typing import Optional
from tqdm import tqdm
from bert_score import BERTScorer
from rouge import Rouge
from statistics import mean
from sklearn.model_selection import train_test_split
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
from torch.nn.functional import binary_cross_entropy_with_logits

torch.manual_seed(42)

tqdm.pandas()
warnings.filterwarnings('ignore')
import transformers
print(transformers.__version__)