# -*- coding: utf-8 -*-
"""Retriever.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBGlp0usbUaQtj0ZTi2oBD1L7FzlLjgP
"""

k3 = 50
retrival_results = []
for i, row in RQETestData.iterrows():
    top_k3_indices, cosine_sim, similar_questions = get_top_k3_similar_questions(row, ArchiveQuestionsVect, ArchiveQuestions, k3)
    retrival_results.append({
        'RQE Question': row['body_Q1'],
        'RQE Answer': row['AnswerBody'],
        'RQE Forum': row['forum_x'],
        'Cosine similarities': cosine_sim,
        'Top n Similar Questions Body': similar_questions['QuestionBody'].tolist(),
        'Top n Candidate Answers': similar_questions['AnswerBody'].tolist(),
        'Top n Similar Questions (Cosine)': top_k3_indices,
        'Top n Similar Questions (id)': similar_questions['QuestionID'].tolist(),
        'Retrieval Time (seconds)': retrieval_time
    })